name: Build and publish Dockerfile

on:
  push:
    branches: [ "main", "test" ]
    paths:
      - 'Dockerfile'
      - 'operator/**'
      - 'src/**'
  pull_request:
    branches: [ "main", "test" ]
    paths:
      - 'Dockerfile'
      - 'operator/**'
      - 'src/**'
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PASS }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: thisisnttheway/${{ github.event.repository.name }}
        tags: |
          # set latest tag for default branch
          type=raw,value=latest
          type=ref,event=branch
        
    - name: Build and push Docker image
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}